//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublicJournal.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.GenericEvents = new HashSet<GenericEvent>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Feedback { get; set; }
    
        public virtual ICollection<GenericEvent> GenericEvents { get; set; }
    }
}
