//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublicJournal.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventRevenue
    {
        public int Id { get; set; }
        public int UserEventHistoryId { get; set; }
        public int Revenue { get; set; }
    
        public virtual UserEventHistory UserEventHistory { get; set; }
    }
}
