//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublicJournal.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventCategory
    {
        public int Id { get; set; }
        public int GenericEventId { get; set; }
        public int CategoryId { get; set; }
    
        public virtual GenericEvent GenericEvent { get; set; }
    }
}
