//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublicJournal.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventTestimonial
    {
        public int Id { get; set; }
        public int EventID { get; set; }
        public int GenericEventID { get; set; }
        public int Rate { get; set; }
        public string Description { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual GenericEvent GenericEvent { get; set; }
    }
}
