//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublicJournal.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightInfo
    {
        public int Id { get; set; }
        public string FlightNo { get; set; }
        public System.DateTime DepartureTime { get; set; }
        public string DepartureAirport { get; set; }
        public System.DateTime LandingTime { get; set; }
        public string LandingAirport { get; set; }
        public int TicketPrice { get; set; }
    }
}
