//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublicJournal.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelInfo
    {
        public HotelInfo()
        {
            this.UserEventHistories = new HashSet<UserEventHistory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ImageFolderPath { get; set; }
        public int Stars { get; set; }
        public decimal RoomPrice { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public int CountryId { get; set; }
        public string ContactEmail { get; set; }
        public string ContactPhone { get; set; }
    
        public virtual ICollection<UserEventHistory> UserEventHistories { get; set; }
    }
}
